AllCops:
  Exclude:
    # Ignore HTML related things
    - '**/*.erb'
    # Ignore vendored gems
    - 'vendor/**/*'
    # Ignore code from test fixtures
    - 'spec/fixtures/**/*'

Lint/ConditionPosition:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

# DISABLED - not useful
Style/HashSyntax:
  Enabled: false

# USES: as shortcut for non nil&valid checking a = x() and a.empty?
# DISABLED - not useful
Style/AndOr:
  Enabled: false

# DISABLED - not useful
Style/RedundantSelf:
  Enabled: false

# DISABLED - not useful
Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# DISABLED - not useful
Style/WhileUntilModifier:
  Enabled: false

# DISABLED - the offender is just haskell envy
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# DISABLED
Security/Eval:
  Enabled: false

# DISABLED
Lint/BlockAlignment:
  Enabled: false

# DISABLED
Lint/DefEndAlignment:
  Enabled: false

# DISABLED
Lint/EndAlignment:
  Enabled: false

# DISABLED
Lint/DeprecatedClassMethods:
  Enabled: false

# DISABLED
Lint/Loop:
  Enabled: false

# DISABLED
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/StringConversionInInterpolation:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/Void:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WhenThen:
  Enabled: false

# DISABLED - not useful
Style/WordArray:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Layout/Tab:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceAroundKeyword:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: false

Layout/SpaceAfterSemicolon:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Layout/DotPosition:
  Enabled: false

# DISABLED - used for converting to bool
Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/Next:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Naming/VariableName:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/For:
  Enabled: false

Style/Lambda:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/RequireParentheses:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/Encoding:
  Enabled: false
